config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from config import settings

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recommendation_system.urls", namespace="recommendation_system")),
    path("users/", include("users.urls", namespace="users")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recommendation_system/urls.py
from django.urls import path

from recommendation_system.apps import RecommendationSystemConfig
from recommendation_system.views import FilmRetrieveAPIView, PreferenceCreateAPIView, RecommendationAPIView, \
    RecommendationStatisticsAPIView, HomePageView, FilmDetailView, RecommendationView, PreferenceView, \
    StatisticRecommendationView

app_name = RecommendationSystemConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('film_detail/<int:pk>/', FilmDetailView.as_view(), name='film_detail'),
    path('recommendation_film/', RecommendationView.as_view(), name='recommendation_film'),
    path('preference/', PreferenceView.as_view(), name='preference'),
    path('statistics/', StatisticRecommendationView.as_view(), name='statistics'),

    path('film/<int:pk>/', FilmRetrieveAPIView.as_view(), name='film'),
    path('add_preference/', PreferenceCreateAPIView.as_view(), name='add-preference'),
    path('recommendation/', RecommendationAPIView.as_view(), name='recommendation'),
    path('recommendation/statistics/', RecommendationStatisticsAPIView.as_view(), name='recommendation_statistics'),
]

users/urls.py
from django.urls import path
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import (TokenObtainPairView, TokenRefreshView)

from users.apps import UsersConfig
from users.views import UserCreateAPIView, UserRetrieveAPIView, RegisterView, LoginUserView, LogoutUserView, \
    ProfileUserDetailView, ProfileUserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('register_web/', RegisterView.as_view(), name='register_web'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('profile/<int:pk>/', ProfileUserDetailView.as_view(), name='profile_user'),
    path('<int:pk>/profile_edit/', ProfileUserUpdateView.as_view(), name='profile_edit'),


    path('register/', UserCreateAPIView.as_view(), name='register'),
    path('<int:pk>/', UserRetrieveAPIView.as_view(), name='user'),
    path('token/', TokenObtainPairView.as_view(permission_classes=[AllowAny]), name='token'),
    path('token/refresh/', TokenRefreshView.as_view(permission_classes=[AllowAny]), name='token_refresh'),
]

recommendation_system/models.py
from django.db import models

from users.models import User


class Genre(models.Model):
    """Модель жанр фильма. Используется для получения предпочтений пользователя"""
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

    def __str__(self):
        return self.name


class Film(models.Model):
    """Модель фильма"""
    title = models.CharField(max_length=255, unique=True, verbose_name="Название фильма")
    description = models.TextField(blank=True, verbose_name="Описание", default="Не указано")
    release_date = models.DateField(verbose_name="Дата выхода")
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='films')
    director = models.CharField(max_length=100, verbose_name="Режиссер")
    rating = models.FloatField(null=True, blank=True, verbose_name="Рейтинг фильма (от 1 до 10)")
    image = models.ImageField(upload_to="recommendation_system/photo/", verbose_name="Изображение",
                              blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)  # Дата создания записи
    updated_at = models.DateTimeField(auto_now=True)  # Дата последнего обновления

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class UserFilm(models.Model):
    """Модель связи: фильма и пользователя (предпочтение)"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='preferences', verbose_name="Пользователь")
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='preferences', verbose_name="Фильм")
    created_at = models.DateTimeField(auto_now_add=True)  # Время взаимодействия

    class Meta:
        verbose_name = "Просмотр фильма пользователем"
        verbose_name_plural = "Просмотры фильма пользователя"
        unique_together = ('user', 'film')  # Обеспечить уникальность предпочтения для каждого пользователя и фильма

    def __str__(self):
        return f"{self.user.username} - посмотрел - {self.film.title}"


class Rating(models.Model):
    """Модель оценки пользователем фильма."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ratings')
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='ratings')
    rating = models.FloatField(verbose_name="Оценка фильма")  # Оценка, например, от 1 до 10
    created_at = models.DateTimeField(auto_now_add=True)  # Время, когда была оставлена оценка

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"
        unique_together = ('user', 'film')  # Пользователь может оценить фильм только один раз

    def __str__(self):
        return f"{self.user.username} оценил {self.film.title} на {self.rating}"


class UserGenre(models.Model):
    """Модель связи пользователя и жанра фильмов"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favorite_genres')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='liked_by_users')

    class Meta:
        unique_together = ('user', 'genre')
        verbose_name = "Жанр пользователя"
        verbose_name_plural = "Жанры пользователя"

    def __str__(self):
        return f"{self.user.username} предпочитает {self.genre.name}"


class RecommendationStatistics(models.Model):
    """Модель статистики рекомендаций для пользователя."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film_count = models.PositiveIntegerField(verbose_name="Количество рекомендованных фильмов", null=True, blank=True,
                                             default=0)
    genre_count = models.PositiveIntegerField(verbose_name="Количество рекомендованных жанров", null=True, blank=True,
                                              default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Статистика {self.user} создана {self.timestamp}"

    class Meta:
        verbose_name = 'Статистика рекомендаций'
        verbose_name_plural = 'Статистики рекомендаций'

recommendation_system/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView
from rest_framework import status
from rest_framework.generics import RetrieveAPIView, CreateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from recommendation_system.models import Film, UserFilm, Genre, UserGenre, Rating, RecommendationStatistics
from recommendation_system.serializers import FilmSerializer, RatingSerializer, UserFilmSerializer, \
    UserGenreSerializer
from recommendation_system.services import RecommendationSystem


class HomePageView(View):
    """Класс представление главной страницы веб-приложения."""
    model = Film
    template_name = "recommendation_system/home.html"
    context_object_name = "films"

    def get(self, request):
        genres = Genre.objects.all()  # Получаем все жанры
        films = Film.objects.all()  # Получаем все фильмы
        # Получаем сообщение об успехе
        success_message = request.session.pop('success_message', None)
        return render(request, self.template_name, {
            'genres': genres,
            'films': films,
            'success_message': success_message,
        })

    def post(self, request):
        if 'genre' in request.POST:
            genre_id = request.POST.get('genre')
            user = request.user

            # Проверяем, существует ли уже этот жанр для пользователя
            if not UserGenre.objects.filter(user=user, genre_id=genre_id).exists():
                UserGenre.objects.create(user=user, genre_id=genre_id)  # Создаем объект UserGenre
                request.session['success_message'] = 'Жанр успешно добавлен!'  # Устанавливаем сообщение об успехе

        elif 'film' in request.POST:
            film_id = request.POST.get('film')
            rating_value = request.POST.get('rating')
            user = request.user

            # Создаем или обновляем оценку для фильма
            Rating.objects.update_or_create(
                user=user,
                film_id=film_id,
                defaults={'rating': rating_value}
            )
            request.session['success_message'] = 'Оценка успешно добавлена!'  # Устанавливаем сообщение об успехе

        return redirect('recommendation_system:home')  # Перенаправление на главную страницу


class FilmDetailView(LoginRequiredMixin, DetailView):
    model = Film
    template_name = "recommendation_system/film.html"
    context_object_name = "film"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user

        if not UserFilm.objects.filter(user=user, film=self.object):
            UserFilm.objects.create(
                user=user,
                film=self.object
            )
        return self.object


@method_decorator(cache_page(60 * 5), name='dispatch')
class RecommendationView(LoginRequiredMixin, ListView):
    model = Film
    template_name = "recommendation_system/recommendation_film.html"
    context_object_name = "film"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        recommendation_system = RecommendationSystem

        graph = recommendation_system.build_preference_graph()
        get_recommendations = recommendation_system.get_recommendations(graph, self.request.user.id)
        _, sorted_pagerank = recommendation_system.calculate_pagerank(graph)

        RecommendationStatistics.objects.create(
            user=self.request.user,
            film_count=len(get_recommendations["films"]),
            genre_count=len(get_recommendations["genres"])
        )

        context["top_5_films"] = Film.objects.filter(title__in=sorted_pagerank["top_5_films"][:4])
        context["top_5_genres"] = Genre.objects.filter(name__in=sorted_pagerank["top_5_genres"])
        context["genres"] = Genre.objects.filter(name__in=get_recommendations["genres"])
        context["films"] = Film.objects.filter(title__in=get_recommendations["films"])

        return context


class PreferenceView(LoginRequiredMixin, ListView):
    model = Rating
    template_name = "recommendation_system/preference_user.html"
    context_object_name = "ratings"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context["user_genres"] = UserGenre.objects.filter(user=self.request.user)
        context["user_films"] = UserFilm.objects.filter(user=self.request.user)
        context["ratings"] = Rating.objects.filter(user=self.request.user)

        return context


class StatisticRecommendationView(LoginRequiredMixin, ListView):
    """Представление статистики рекомендаций для пользователя."""
    model = RecommendationStatistics
    template_name = "recommendation_system/statistics.html"
    context_object_name = "statistics"

    def get_queryset(self):
        return RecommendationStatistics.objects.filter(user=self.request.user)


class FilmRetrieveAPIView(RetrieveAPIView):
    """Класс представления фильма через RetrieveAPIView"""
    queryset = Film.objects.all()
    serializer_class = FilmSerializer

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        user = request.user

        if not UserFilm.objects.filter(user=user, film=instance):
            UserFilm.objects.create(
                user=user,
                film=instance
            )
        return Response(self.get_serializer(instance).data)


class PreferenceCreateAPIView(CreateAPIView):
    """Класс представления для добавления предпочтений пользователю"""
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        # Устанавливаем текущего пользователя перед сохранением
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        data = request.data

        # Проверяем тип данных и создаем соответствующий объект
        if 'rating' in data and 'film' in data:
            serializer = RatingSerializer(data=data)
        elif 'genre' in data:
            serializer = UserGenreSerializer(data=data)
        elif 'film' in data:
            serializer = UserFilmSerializer(data=data)
        else:
            return Response({
                "error": "Укажите предпочтения: 'rating', 'film' или 'genre' или 'film'."
            },
                status=status.HTTP_400_BAD_REQUEST)

        if serializer.is_valid():
            self.perform_create(serializer)  # Вызываем perform_create
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RecommendationAPIView(APIView):
    """API для получения рекомендаций на основе графов"""
    permission_classes = [IsAuthenticated]

    def get(self, request):
        recommendation_system = RecommendationSystem

        graph = recommendation_system.build_preference_graph()
        get_recommendations = recommendation_system.get_recommendations(graph, request.user.id)
        _, sorted_pagerank = recommendation_system.calculate_pagerank(graph)

        RecommendationStatistics.objects.create(
            user=request.user,
            film_count=len(get_recommendations["films"]),
            genre_count=len(get_recommendations["genres"])
        )

        return Response({"top": sorted_pagerank, "recommendations": get_recommendations})


class RecommendationStatisticsAPIView(APIView):
    """API для получения статистики на основе графов и рекомендаций."""
    permission_classes = [IsAuthenticated]

    def get(self, request):
        system = RecommendationSystem
        graph = system.build_preference_graph()

        # Получаем статистику рекомендации для текущего пользователя
        pagerank_scores, _ = system.calculate_pagerank(graph)
        similar_users = system.collaborative_filtering(graph, request.user.id)
        k_neighbors = system.k_nearest_neighbors(graph, request.user.id)

        return Response({
            'pagerank_scores': pagerank_scores,
            'similar_users': similar_users,
            'k_neighbors': k_neighbors
        })

recommendation_system/templates/recommendation_system/film.html
{% extends 'recommendation_system/includes/basic_design.html' %}
{% load my_tags %}
{% block title %}Главная страница{% endblock %}

{% block header %}
{% include 'recommendation_system/includes/header_menu.html' %}

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="row text-center" >
    <div class="card mb-4 box-shadow" style="background: rgba(255, 255, 255, 0.7); box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);">
        <div class="card-header">
            <img src="{{film.image | media_filter}}" width="250" height="250">
            <h1 class="my-0 font-weight-normal">{{ film.title }}</h1>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>- Жанр: {{film.genre}}</li>
                <li>- Дата релиза: {{film.release_date | date:"d M Y"}}</li>
                <li>- Режиссёр: {{film.director}}</li>
                <li>- Рейтинг: {{film.rating}}</li>
            </ul>
            <h2 class="card-title pricing-card-title">{{film.description|truncatechars:250}}</h2>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

recommendation_system/templates/recommendation_system/home.html
{% extends 'recommendation_system/includes/basic_design.html' %}
{% load my_tags %}
{% block title %}Главная страница{% endblock %}

{% block header %}
{% include 'recommendation_system/includes/header_menu.html' %}
<div class="container mt-1 mb-5">

    <div class="d-flex align-items-center mb-3">
        <button class="btn btn-outline-light me-2" id="prevButton" style="opacity: 0.8;">
            <span class="material-icons">Назад</span>
        </button>

        <div class="movie-carousel flex-grow-1">
            <div class="row" id="movieRow">
                <!-- Здесь будут карточки фильмов -->
                {% for film in films %}
                <div class="col-6 col-md-3 movie-card">
                    {% if user.is_authenticated %}
                    <a href="{% url 'recommendation_system:film_detail' film.id %}" class="card mb-4 shadow-sm"
                       style="background-color: rgba(255, 255, 255, 0.8); border: none; text-decoration: none;">
                        <img src="{{ film.image | media_filter}}" width="175" height="130" class="card-img-top"
                             alt="{{ movie.title }}" style="opacity: 1;">
                        <div class="card-body">
                            <h5 class="card-title text-center" style="opacity: 1;">{{film.title|truncatechars:16}}</h5>
                        </div>
                    </a>
                    {% else %}
                    <div class="card mb-4 shadow-sm"
                         style="background-color: rgba(255, 255, 255, 0.8); border: none; text-decoration: none;">
                        <img src="{{ film.image | media_filter}}" width="175" height="130" class="card-img-top"
                             alt="{{ movie.title }}" style="opacity: 1;">
                        <div class="card-body">
                            <h5 class="card-title text-center" style="opacity: 1;">{{film.title|truncatechars:16}}</h5>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>

        <button class="btn btn-outline-light ms-2" id="nextButton" style="opacity: 0.8;">
            <span class="material-icons">Вперед</span>
        </button>
    </div>
</div>

<script>
    let currentIndex = 0; // Начальный индекс
    const moviesPerPage = 4; // Количество фильмов на странице
    const movieCards = document.querySelectorAll('.movie-card'); // Все карточки фильмов

    function showMovies() {
        // Скрыть все карточки
        movieCards.forEach((card, index) => {
            if (index >= currentIndex && index < currentIndex + moviesPerPage) {
                card.style.display = 'block'; // Показать карточки для текущей страницы
            } else {
                card.style.display = 'none'; // Скрыть остальные
            }
        });
    }

    document.getElementById('prevButton').addEventListener('click', () => {
        if (currentIndex > 0) {
            currentIndex -= moviesPerPage; // Уменьшаем индекс
            showMovies(); // Обновляем отображение
        }
    });

    document.getElementById('nextButton').addEventListener('click', () => {
        if (currentIndex + moviesPerPage < movieCards.length) {
            currentIndex += moviesPerPage; // Увеличиваем индекс
            showMovies(); // Обновляем отображение
        }
    });

    // Инициализация отображения
    showMovies();
</script>
{% endblock %}

{% block content %}
{% if not user.is_authenticated %}
<div class="container text-center shadow p-3 mb-5 bg-body-tertiary rounded" style="opacity: 0.7;">
    <h2>
        Чтобы мы могли предоставить вам качественную рекомендацию,
        пожалуйста, войдите или зарегистрируйтесь!
    </h2>
</div>
{% else %}
<div class="row text-center mt-5 mb-5"></div>
<div class="row text-center mt-5 mb-5"></div>
<div class="row text-center mt-5 mb-5">
    <div class="col-4"></div>
    <div class="col-4">
        <a class="btn btn-dark shiny-button" href="{% url 'recommendation_system:recommendation_film' %}">Получить рекомендацию</a>
    </div>
    <div class="col-4"></div>
</div>

<style>
    .shiny-button {
        padding: 15px 30px; /* Отступы для кнопки */
        font-size: 18px; /* Размер шрифта */
        border-radius: 25px; /* Скругление углов для объемного эффекта */
        position: relative; /* Для абсолютного позиционирования псевдоэлемента */
        overflow: hidden; /* Скрыть за пределами кнопки */
        transition: background-color 0.3s ease; /* Плавный переход цвета фона */
    }

    .shiny-button:hover {
        background-color: #343a40; /* Цвет фона при наведении */
    }

    .shiny-button::before {
        content: ''; /* Псевдоэлемент перед кнопкой */
        position: absolute;
        top: -200%; /* Начальная позиция выше кнопки */
        left: -200%; /* Начальная позиция слева кнопки */
        width: 300%; /* Ширина блеска */
        height: 300%; /* Высота блеска */
        background: linear-gradient(45deg, rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0.3));
        transition: transform 2.5s ease; /* Плавный переход для анимации */
        transform: translate(0, 0); /* Начальная позиция */
    }

    .shiny-button:hover::before {
        transform: translate(200%, 200%); /* Перемещение блеска при наведении */
    }
</style>
<div class="row text-center ">
    <div class="col-6">
        <div class="genre-container mt-5">
            <h3>Выберите любимые жанры фильмов</h3>
            <form method="POST" action="{% url 'recommendation_system:home' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select name="genre" class="form-select" required>
                        <option value="" disabled selected>Выберите жанр</option>
                        {% for genre in genres %}
                        <option value="{{ genre.id }}">{{ genre.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-outline-dark mt-2">Добавить жанр</button>
                {% if success_message == 'Жанр успешно добавлен!' %}
                <button class="btn btn-success mt-2" disabled><i class="bi bi-check"></i> {{ success_message }}</button>
                {% endif %}
            </form>
        </div>
    </div>

    <div class="col-6">
        <div class="rating-container mt-5">
            <h3>Оцените фильм</h3>
            <form method="POST" action="{% url 'recommendation_system:home' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select name="film" class="form-select" required>
                        <option value="" disabled selected>Выберите фильм</option>
                        {% for film in films %}
                        <option value="{{ film.id }}">{{ film.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group mt-2">
                    <label for="rating">Оценка (1-10):</label>
                    <input type="number" name="rating" id="rating" class="form-control" min="1" max="10" required>
                </div>
                <button type="submit" class="btn btn-outline-dark mt-2">Добавить оценку</button>
                {% if success_message == 'Оценка успешно добавлена!'%}
                <button class="btn btn-success mt-2" disabled><i class="bi bi-check"></i> {{ success_message }}</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
<style>
    .genre-container, .rating-container {
        background-color: rgba(255, 255, 255, 0.9); /* Полупрозрачный белый цвет */
        padding: 20px; /* Отступы для контейнера */
        border-radius: 10px; /* Скругление углов */
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2); /* Тень для объема */
        margin-bottom: 20px; /* Отступ снизу между контейнерами */
    }

    h3 {
        color: #333; /* Цвет заголовка */
    }

    .form-select, .form-control {
        opacity: 1; /* Убедитесь, что элементы форм не прозрачные */
    }

    .btn-primary {
        background-color: #007bff; /* Цвет кнопки */
        border: none; /* Убираем границу */
    }

    .btn-primary:hover {
        background-color: #0056b3; /* Цвет кнопки при наведении */
    }
</style>
{% endif %}
{% endblock %}

recommendation_system/templates/recommendation_system/recommendation_film.html
{% extends 'recommendation_system/includes/basic_design.html' %}
{% load my_tags %}
{% block title %}Главная страница{% endblock %}

{% block header %}
{% include 'recommendation_system/includes/header_menu.html' %}
<div class="container mt-1 mb-5">
    <div class="row">
        <div class="col-12 text-center">
            <div class="shadow p-3 mb-1 bg-body-tertiary rounded"
                 style="opacity: 0.7; max-width: 400px; margin: 0 auto;">
                <h2>
                    Топ фильмы месяца
                </h2>
            </div>
        </div>

        {% for film in top_5_films %}
        <div class="col-6 col-md-3 movie-card">
            <a href="{% url 'recommendation_system:film_detail' film.id %}" class="card mb-4 shadow-sm"
               style="background-color: rgba(255, 255, 255, 0.8); border: none; text-decoration: none;">
                <img src="{{ film.image | media_filter}}" width="175" height="130" class="card-img-top"
                     alt="{{ movie.title }}" style="opacity: 1;">
                <div class="card-body">
                    <h5 class="card-title text-center" style="opacity: 1;">{{film.title|truncatechars:16}}</h5>
                    <h5 class="card-title text-center" style="opacity: 1;">Рейтинг: {{film.rating}}</h5>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>

    <div class="row text-center mt-5 mb-5"></div>
    <div class="row text-center mt-5 mb-5"></div>

    <div class="container text-center">
        <div class="shadow p-3 mb-1 bg-body-tertiary rounded" style="opacity: 0.9; max-width: 400px; margin: 0 auto;">
            <h2>
                Топ жанры фильмов
            </h2>
        </div>
    </div>

    <div class="container text-center">
        <div class="shadow p-3 mb-1 bg-body-tertiary rounded" style="opacity: 0.9;">
            <div class="row">
                {% for film in top_5_genres %}
                <div class="col-2 container text-center shadow p-3 mb-1 bg-body-tertiary rounded" style="opacity: 1;">
                    <h5 class="card-title text-center" style="opacity: 1;">{{film.name|truncatechars:16}}</h5>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="row text-center mt-5 mb-5"></div>
<div class="row text-center mt-5 mb-5"></div>
<div class="row text-center mt-5 mb-5"></div>
<div class="row text-center mt-5 mb-5"></div>
<div class="row text-center mt-5 mb-5"></div>
<div class="row text-center mt-5 mb-5">
    <div class="container text-center">
        <div class="shadow p-3 mb-1 bg-body-tertiary rounded" style="opacity: 0.9; max-width: 400px; margin: 0 auto;">
            <h2>
                Ваши рекомендации
            </h2>
        </div>
        <div class="shadow p-3 mb-1 bg-body-tertiary rounded" style="opacity: 0.9;">
            <div class="row">
                {% for film in genres %}
                <div class="col-2 container text-center shadow p-3 mb-1 bg-body-tertiary rounded" style="opacity: 1;">
                    <h5 class="card-title text-center" style="opacity: 1;">{{film.name|truncatechars:16}}</h5>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="row">
    {% for film in films %}
    <div class="col-6 col-md-3 movie-card">
        <a href="{% url 'recommendation_system:film_detail' film.id %}" class="card mb-4 shadow-sm"
           style="background-color: rgba(255, 255, 255, 0.8); border: none; text-decoration: none;">
            <img src="{{ film.image | media_filter}}" width="175" height="130" class="card-img-top"
                 alt="{{ movie.title }}" style="opacity: 1;">
            <div class="card-body">
                <h5 class="card-title text-center" style="opacity: 1;">{{film.title|truncatechars:16}}</h5>
                <h5 class="card-title text-center" style="opacity: 1;">Рейтинг: {{film.rating}}</h5>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}