config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from config import settings

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recommendation_system.urls", namespace="recommendation_system")),
    path("users/", include("users.urls", namespace="users")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recommendation_system/urls.py
from django.urls import path

from recommendation_system.apps import RecommendationSystemConfig
from recommendation_system.views import FilmRetrieveAPIView, PreferenceCreateAPIView, RecommendationAPIView, \
    RecommendationStatisticsAPIView, HomePageView, FilmDetailView, RecommendationView, PreferenceView, \
    StatisticRecommendationView

app_name = RecommendationSystemConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('film_detail/<int:pk>/', FilmDetailView.as_view(), name='film_detail'),
    path('recommendation_film/', RecommendationView.as_view(), name='recommendation_film'),
    path('preference/', PreferenceView.as_view(), name='preference'),
    path('statistics/', StatisticRecommendationView.as_view(), name='statistics'),

    path('film/<int:pk>/', FilmRetrieveAPIView.as_view(), name='film'),
    path('add_preference/', PreferenceCreateAPIView.as_view(), name='add-preference'),
    path('recommendation/', RecommendationAPIView.as_view(), name='recommendation'),
    path('recommendation/statistics/', RecommendationStatisticsAPIView.as_view(), name='recommendation_statistics'),
]

users/urls.py
from django.urls import path
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import (TokenObtainPairView, TokenRefreshView)

from users.apps import UsersConfig
from users.views import UserCreateAPIView, UserRetrieveAPIView, RegisterView, LoginUserView, LogoutUserView, \
    ProfileUserDetailView, ProfileUserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('register_web/', RegisterView.as_view(), name='register_web'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('profile/<int:pk>/', ProfileUserDetailView.as_view(), name='profile_user'),
    path('<int:pk>/profile_edit/', ProfileUserUpdateView.as_view(), name='profile_edit'),


    path('register/', UserCreateAPIView.as_view(), name='register'),
    path('<int:pk>/', UserRetrieveAPIView.as_view(), name='user'),
    path('token/', TokenObtainPairView.as_view(permission_classes=[AllowAny]), name='token'),
    path('token/refresh/', TokenRefreshView.as_view(permission_classes=[AllowAny]), name='token_refresh'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = models.CharField(max_length=255, unique=True, verbose_name='Никнейм')
    name = models.CharField(max_length=128, null=True, blank=True, default="Не указано",
                            verbose_name="Имя пользователя")
    country = models.CharField(max_length=128, null=True, blank=True, default="Не указано",
                               verbose_name="Страна")
    city = models.CharField(max_length=128, null=True, blank=True, default="Не указано",
                            verbose_name="Город")
    avatar = models.ImageField(upload_to="users/photo/", verbose_name="Аватар", blank=True, null=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.username}"

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User
from .services import FormClean


class ProfileForm(FormClean, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Придумайте ваш Никнейм.',
            'help_text': "!@@@@@"
        })
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Ваше имя',
            'help_text': "!@@@@@"
        })
        self.fields['country'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Выберите страну'
        })
        self.fields['avatar'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['city'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Выберите город'
        })

    class Meta:
        model = User
        fields = ('username', 'name', 'country', 'avatar', 'city',)
        exclude = ('password1', 'password2')

    def clean_password(self):
        password = self.cleaned_data.get('password')
        password_user = User.objects.get(password=password)
        return password_user.password

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if User.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("Пользователь с таким username уже существует.")

        return username

    def clean(self):
        """Валидация на проверку полей (чтобы не было запрещенных слов)"""
        super().clean()


class LoginUserForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите ваш username'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })


class CustomUserCreationForm(FormClean, UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите ваш никнейм.'
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-select'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-select'
        })

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

    def clean(self):
        """Валидация на проверку полей (чтобы не было запрещенных слов)"""
        super().clean()

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, UpdateView, CreateView
from rest_framework.generics import CreateAPIView, RetrieveAPIView
from rest_framework.permissions import AllowAny, IsAuthenticated

from users.forms import CustomUserCreationForm, LoginUserForm, ProfileForm
from users.models import User
from users.permissions import IsOwner
from users.serializers import UserSerializer, UserRetrieveSerializer
from users.services import UserIsNotAuthenticated


class UserCreateAPIView(CreateAPIView):
    """Реализация представления регистрации пользователя, через CreateAPIView."""
    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [AllowAny]

    def perform_create(self, serializer):
        """Хэшируем пароль при создании пользователя."""
        user = serializer.save(is_active=True)
        user.set_password(serializer.validated_data['password'])
        user.save()


class UserRetrieveAPIView(RetrieveAPIView):
    """Реализация представления просмотра пользователя, через RetrieveAPIView."""
    serializer_class = UserRetrieveSerializer
    queryset = User.objects.all()
    # IsOwner добавлен permissions.py для просмотра пользователя только самим пользователем
    permission_classes = [IsAuthenticated, IsOwner]


class ProfileUserDetailView(LoginRequiredMixin, DetailView):
    """Представление просмотра профиля пользователя на веб-сервере"""
    model = User
    template_name = 'users/profile_user.html'
    context_object_name = 'profile_user'

    def get_object(self, queryset=None):
        """Проверяем что пользователь может смотреть только свой профиль"""
        self.object = super().get_object(queryset)
        user_id = self.request.user.id
        return IsOwner.get_object_only_owner(self=self.object, user_id=user_id)


class ProfileUserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/register.html'
    form_class = ProfileForm

    context_object_name = "profile_edit"

    def get_success_url(self):
        return reverse("users:profile_user", args=[self.kwargs.get("pk")])

    def get_object(self, queryset=None):
        """Проверяем что пользователь может смотреть только свой профиль"""
        self.object = super().get_object(queryset)
        user_id = self.request.user.id
        return IsOwner.get_object_only_owner(self=self.object, user_id=user_id)


class LoginUserView(UserIsNotAuthenticated, LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'


class LogoutUserView(LoginRequiredMixin, LogoutView):
    success_url = reverse_lazy('recommendation_system:home')
    next_page = 'recommendation_system:home'


class RegisterView(UserIsNotAuthenticated, CreateView):
    template_name = 'users/register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('recommendation_system:home')

users/templates/users/login.html
{% extends 'recommendation_system/includes/basic_design.html' %}
{% load my_tags %}
{% block title %}Вход{% endblock %}

{% block header %}
{% include 'recommendation_system/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4 text-white">Вход на сайт</h1>
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-4"></div>
    <div class="col-4 text-center shadow p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
            <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-dark ms-2">
                        Войти
                    </button>
                    <a class="btn btn-lg btn-block btn-dark"
                       href="{% url 'recommendation_system:home' %}">Назад</a>
                </div>
            </form>
        </div>
    </div>
    <div class="col-4"></div>
</div>
{% endblock %}

users/templates/users/profile_user.html
{% extends 'recommendation_system/includes/basic_design.html' %}
{% load my_tags %}
{% block title %}Профиль{% endblock %}

{% block header %}
{% include 'recommendation_system/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4 text-white">Профиль</h1>
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-3"></div>
    <div class="card-body col-6 text-center">
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <h3 class="form-label">Никнейм</h3>
            <h1 class="form-control">{{ profile_user.username }}</h1>

            <h3 class="form-label">Имя пользователя</h3>
            <h1 class="form-control">{{ profile_user.name }}</h1>

            <h3 class="form-label">Город</h3>
            <h1 class="form-control">{{ profile_user.city }}</h1>

            <h3 class="form-label">Страна</h3>
            <h1 aria-label="Disabled input example" class="form-control">{{ profile_user.country }}</h1>

            <h3 class="form-label">Аватар</h3>
            <img src="{{ profile_user.avatar | media_filter }}" class="image" width="200" height="200">
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <a class="btn btn-lg btn-block btn-outline-dark ms-2" href="{% url 'users:profile_edit' profile_user.pk%}">Редактировать</a>
                <a class="btn btn-lg btn-block btn-dark"
                   href="{% url 'recommendation_system:home' %}">Назад</a>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'recommendation_system/includes//basic_design.html' %}
{% load my_tags %}
{% block title %}Регистрация{% endblock %}

{% block header %}
{% include 'recommendation_system/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        {% if user.is_active %}
            Обновление профиля
        {% else %}
            Регистрация
        {% endif %}
    </h1>
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-3"></div>
        <div class="card-body col-6 text-center shadow p-3 mb-5 bg-body-tertiary rounded">
            <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    {{ form.non_field_errors }}
                    {{ form.as_p }}
                    {% if user.is_active %}
                        <button type="submit" class="btn btn-lg btn-block btn-dark">
                            Сохранить
                        </button>
                        <a class="btn btn-lg btn-block btn-outline-dark"
                           href="{% url 'users:profile_user' user.pk %}">Назад</a>
                    {% else %}
                        <button type="submit" class="btn btn-lg btn-block btn-dark">
                            Регистрация
                        </button>
                        <a class="btn btn-lg btn-block btn-outline-dark"
                           href="{% url 'recommendation_system:home' %}">Назад</a>
                    {% endif %}
                </div>
            </form>
        </div>
    <div class="col-3"></div>
</div>
{% endblock %}